#!/bin/bash
sudo yum update -y

sudo yum install epel-release -y
sudo yum install nginx -y

sudo systemctl start nginx
sudo systemctl enable nginx

sudo timedatectl set-timezone America/Sao_Paulo
sudo echo $HOSTNAME >> /usr/share/doc/HTML/index.html

#sudo firewall-cmd --permanent --zone=public --add-service=http 
#sudo firewall-cmd --permanent --zone=public --add-service=https
sudo firewall-offline-cmd --add-service=http 
sudo firewall-offline-cmd --add-service=https

sudo firewall-cmd --reload
#sudo systemctl restart firewalld